title: Matrix PSTN Bridge
description: ☎️ A Matrix Puppet bridge for the public telephone network that supports a number of VoIP providers (Twillo, Vonage, etc.). Sends and receives voice and SMS.
remote_theme: pmarsceill/just-the-docs

aux_links:
  "On GitHub":
    - "https://github.com/kb1rd/matrix-pstn-bridge/"

aux_links_new_tab: true

